### PR TITLE
Add a web hook when a marketplace page is visited

### PR DESCRIPTION
**Pull request by danielgasser**

### CODE REVIEW

**Comment by a3020** [comment]
I think it's too heavy to send this information via PHP. Maybe @mnakalay has ideas about this?

**Comment by mnakalay** [comment]
Piwik is very limited in what it can give you. It more or less gives you information concerning page views and how long someone stayed on a page.
Sometimes it is able to tell you where they came from and where they went from there but not always.

But for all we know it could be bots. It could be just a site checking for updates.. it's hard to tell. You might notice sometimes a referal URL is from some site's dashboard update page.

@a3020 I am not sure I understand what you are referring to. What is too heavy?

**Comment by a3020** [comment]
Maybe we should move this to an 'issue'. But I think that it's too heavy to send a request to a webhook every time a visitor visits a marketplace page. A JS solution, integration with 3rd party system, an API to retrieve stats, or a webhook to periodically send stats would for example make more sense to me.

**Comment by mnakalay** [comment]
The webhook wouldn't be for visits. I agree that would be too much.

It would be, like I wrote, for sales, licenses attachment to projects, and refunds, which all happen only a limited number of times and for which I am sure they already do some event triggering.

ANother thing I said is I don't think the core team will be willing to provide us with stats about market views and stuff like that. First I was told in no uncertain terms that it would be a huge undertaking and the core team didn't have the bandwidth for that. Second, the idea is because we can use Piwik pixel tracking, that's good enough for now.

My idea for webhooks is based on several reasons:
1- The core team doesn't need to do much. They most likely already have the data I discussed since that's what we are getting by email (for sales anyway) so it's just a matter of sending it to the seller's webhook. No big deal. They don't need to process the data for us. We use it or not up to us. The pressure of data processing is on us.
2- That's data we can use right away if we want to. On the other hand, knowing how many people go to the marketplace every day or how many sales there are every day don't tell me much. All I can do with that is decide if it's worth it or not. If I could get data by category of plugins for instance that might be helpful but I'm pretty sure we won't get that. We can always ask if enough people want it.
3- That's information that can help us make dealing with our buyers automatic to some extent and that can help us get back part of the process and have a direct connection to our buyers which, in my mind anyway, is extremely important.

But maybe I am not seeing it the way you do. What kind of stats would you see as useful? And what would you do with it if you had it?

**Comment by a3020** [comment]
I think we should close this in favor of an API call to retrieve statistics. Mean reason is that the solution wouldn't be scalable. Imagine a DDOS attack on a marketplace page :)

**Comment by mnakalay** [comment]
I'm a bit surprised, in Issue #7 you were for proposing both ideas to the C5 team and let them choose.

I didn't add anything in my proposal concerning page views. I focused purely on sale.

Do you think a DDOS attack could fake PayPal payments, refunds... that wouldn't be a DDOS attack, that would be compromised accounts.

But anyway, if it's closed, it's closed.

**Comment by mnakalay** [comment]
Sorry for my last comment, I need to get some sleep.

**Pull request closed without merging**
